### ISSUE TITLE
LGPL or GPL?

### ISSUE THREAD

**Issue by nemequ** [akamiru/bce#8]
README says LGPL, but the comments in the source code say GPL.

**Comment by akamiru** [comment]
That's due to the fact that I simply copied the text from the GPL homepage. All code is supposed to be LGPL. I'll reconsider switching to MIT to make my intentions more clear.

**Comment by nemequ** [comment]
I'm fond of MIT (I use if for Squash), but LGPL is fine if that's what you want.  You can copy the correct declaration from https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html#SEC4 (for LGPLv2.1+).  If you would like to use v3, or get rid if the "or any later version" part it's easy to change.

**Comment by akamiru** [comment]
Clean-up branch switched to MIT and will be merged as soon as I improved the quality of the command line tool.
